### ISSUE TITLE
FATFAT

### ISSUE THREAD

**Issue by AnujCtrl** [PramitKumar27/101python#1]
Oh dear friend, let me sing to thee,
of a language that's simple and free,
Python's the name, it's clear to see,
a joy to learn, it will set you free.

With its elegance and ease of use,
you'll find coding is no longer a muse,
for it'll guide you through every bend,
and help you create, till the very end.

It's a treasure, a pearl, a shining star,
a skill that'll take you very far,
in the world of tech, it's a shining car,
that'll open doors, both near and afar.

So don't hesitate, don't delay,
start learning Python today,
for it's the key, to a brighter way,
a path to success, come what may.

With every line, you'll feel the power,
that comes with each passing hour,
and soon you'll see, in this language flower,
an endless potential, in each and every tower.

So dear friend, take up this quest,
Python is the language, that's truly blessed,
and with each step, you'll be at your best,
and your future will be, truly impressed.

**Comment by AnujCtrl** [comment]
nhk

**Comment by PramitKumar27** [comment]
spam kyu kr rha

**Comment by AnujCtrl** [comment]
> 



> spam kyu kr rha

poem beja me
